### ISSUE TITLE
getting syntax error

### ISSUE THREAD

**Issue by arslan2012** [ruby/TryRuby#20]
I'm using ruby.github.io/TryRuby/ and progressed to ***Me hungry***  chapter
this is what I wrote
``` ruby
def hungry?(time_of_day_in_hours)
  if time_of_day_in_hours > 12
  	puts "Me hungry."
    true
  else
    puts "Me not hungry."
    false
  end
end

def eat_an(what)
  puts "Me eat #{what}.\n"
end

eat_an 'apple' if hungry?(14)

eat_an 'apple' if hungry?(10)
```
but the website keeps telling me I have a syntax error
```
SyntaxError: An error occurred while compiling: (file)

unexpected '"kELSE"'
Source: (file):3:6
  	puts "Me hungry."
~~~~~^

SyntaxError: An error occurred while compiling: (file)

unexpected '"kELSE"'
Source: (file):3:6
  	puts "Me hungry."
~~~~~^
    at n.$new (https://ruby.github.io/TryRuby/javascripts/application.js:2:1795)
    at a.<anonymous> (https://ruby.github.io/TryRuby/javascripts/application.js:1:30709)
    at a.p.$compile (https://ruby.github.io/TryRuby/javascripts/application.js:15:2264)
    at e.$compile (https://ruby.github.io/TryRuby/javascripts/application.js:15:243)
    at $TryRuby.def.$do_run (https://ruby.github.io/TryRuby/javascripts/application.js:16:26859)
    at n (https://ruby.github.io/TryRuby/javascripts/application.js:16:21778)
    at HTMLButtonElement.o (https://ruby.github.io/TryRuby/javascripts/application.js:15:29218)
    at HTMLButtonElement.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js:3:12444)
    at HTMLButtonElement.r.handle (https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js:3:9173)
```

I tried the code in irb, but in irb it runs correctly.
anyone knows why?

**Comment by easydatawarehousing** [comment]
Thanks for reporting this issue. Cause seems to be the tab before `puts "Me hungry.` When I replace the tab by spaces the code runs as expected. I suspect that a newer opal-parser version fixes this issue. I will look into it.

**Comment by pagangil** [comment]
@easydatawarehousing  I'm also hitting this issue even when I'm using `spaces` instead of `tabs` as suggested in the workaround

**Comment by easydatawarehousing** [comment]
I have updated a lot of gems including Opal. Works for me now [here](https://easydatawarehousing.github.io/TryRuby/). Still needs to be updated on the fork of this repo that ruby-lang.org uses.

**Comment by easydatawarehousing** [comment]
In production.
