### ISSUE TITLE
`<class:Thor>': superclass mismatch for class Command (TypeError)

### ISSUE THREAD

**Issue by husseinamine** [ruby/TryRuby#86]
```
Traceback (most recent call last):
	22: from /usr/local/bin/middleman:23:in `<main>'
	21: from /usr/local/bin/middleman:23:in `load'
	20: from /var/lib/gems/2.7.0/gems/middleman-cli-4.3.6/bin/middleman:49:in `<top (required)>'
	19: from /var/lib/gems/2.7.0/gems/middleman-cli-4.3.6/bin/middleman:49:in `new'
	18: from /var/lib/gems/2.7.0/gems/middleman-core-4.3.6/lib/middleman-core/application.rb:263:in `initialize'
	17: from /var/lib/gems/2.7.0/gems/middleman-core-4.3.6/lib/middleman-core/application.rb:263:in `new'
	16: from /var/lib/gems/2.7.0/gems/middleman-core-4.3.6/lib/middleman-core/extension_manager.rb:12:in `initialize'
	15: from /var/lib/gems/2.7.0/gems/middleman-core-4.3.6/lib/middleman-core/extensions.rb:125:in `load_settings'
	14: from /var/lib/gems/2.7.0/gems/middleman-core-4.3.6/lib/middleman-core/extensions.rb:125:in `each'
	13: from /var/lib/gems/2.7.0/gems/middleman-core-4.3.6/lib/middleman-core/extensions.rb:127:in `block in load_settings'
	12: from /var/lib/gems/2.7.0/gems/middleman-core-4.3.6/lib/middleman-core/extensions.rb:91:in `load'
	11: from /var/lib/gems/2.7.0/gems/middleman-blog-4.0.3/lib/middleman-blog.rb:6:in `block in <top (required)>'
	10: from /var/lib/gems/2.7.0/gems/middleman-blog-4.0.3/lib/middleman-blog.rb:6:in `require'
	 9: from /var/lib/gems/2.7.0/gems/middleman-blog-4.0.3/lib/middleman-blog/commands/article.rb:5:in `<top (required)>'
	 8: from /var/lib/gems/2.7.0/gems/middleman-blog-4.0.3/lib/middleman-blog/commands/article.rb:6:in `<module:Middleman>'
	 7: from /var/lib/gems/2.7.0/gems/middleman-blog-4.0.3/lib/middleman-blog/commands/article.rb:18:in `<module:Cli>'
	 6: from /var/lib/gems/2.7.0/gems/middleman-blog-4.0.3/lib/middleman-blog/commands/article.rb:18:in `require'
	 5: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:1:in `<top (required)>'
	 4: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:1:in `require_relative'
	 3: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:1:in `<top (required)>'
	 2: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:1:in `require_relative'
	 1: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:1:in `<top (required)>'
/var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:2:in `<class:Thor>': superclass mismatch for class Command (TypeError)
rake aborted!
Command failed with status (1): [bundle exec middleman build --clean...]
/var/lib/gems/2.7.0/gems/middleman-gh-pages-0.4.1/lib/middleman-gh-pages/tasks/gh-pages.rake:79:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.7.0/gems/middleman-gh-pages-0.4.1/lib/middleman-gh-pages/tasks/gh-pages.rake:78:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.7.0/gems/middleman-gh-pages-0.4.1/lib/middleman-gh-pages/tasks/gh-pages.rake:21:in `block in backup_and_restore'
/var/lib/gems/2.7.0/gems/middleman-gh-pages-0.4.1/lib/middleman-gh-pages/tasks/gh-pages.rake:19:in `backup_and_restore'
/var/lib/gems/2.7.0/gems/middleman-gh-pages-0.4.1/lib/middleman-gh-pages/tasks/gh-pages.rake:77:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
```

this errors always hits when i run ``` bundle exec middleman server```

**Comment by husseinamine** [comment]
i fixed it by running 
```
gem install bundler
```
